fix: workflow actions-coverage-v19

diff --git a/.github/workflows/ci-release-production.yml b/.github/workflows/ci-release-production.yml
--- a/.github/workflows/ci-release-production.yml
+++ b/.github/workflows/ci-release-production.yml
@@ -13,14 +13,17 @@ on:
 
 jobs: 
 
-  build-to-dev:
+  build-release-main:
     name: Build Python 🐍
     
     environment:
       name: development
       #url: 'https://rancher-finance-stage.99app.com/'
       
-    
+    env:
+      COVERAGE_SINGLE: 60
+      COVERAGE_TOTAL: 60
+
     strategy:
       fail-fast: false
       matrix:
@@ -105,12 +108,59 @@ jobs:
 
 
       #----------------------------------------------
-      #Run coverage tests
+      #Run coverage report
       #----------------------------------------------
       - name: pytest-coverage-commentator
         if: github.event_name == 'pull_request'
         uses: coroo/pytest-coverage-commentator@v1.0.2
         with:
           pytest-coverage: pytest-coverage.txt
-      
-      
+
+
+      #----------------------------------------------
+      #Run coverage tests
+      #----------------------------------------------
+      - name: Coverage test pytester-cov
+        id: pytester-cov
+        uses: alexanderdamiani/pytester-cov@v1.2.3
+        with:
+          pytest-root-dir: 'simplecalc/.'
+          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+
+      - name: Coverage single fail - new issue
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        uses: nashmaniac/create-issue-action@v1.1
+        with:
+          title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          labels: workflow-failed
+          body: ${{ steps.pytester-cov.outputs.output-table }}
+
+      - name: Coverage single fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+          exit 1
+
+      - name: Coverage total fail - new issue
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        uses: nashmaniac/create-issue-action@v1.1
+        with:
+          title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          labels: workflow-failed
+          body: ${{ steps.pytester-cov.outputs.output-table }}
+
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+          exit 1
+
+      - name: Commit pytest coverage table
+        uses: peter-evans/commit-comment@v1
+        with:
+          body: ${{ steps.pytester-cov.outputs.output-table }}
